import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

const SEED_PROBLEMS = [
  {
    title: "소규모 자영업자의 재고·발주 관리 비효율",
    who: "카페·식당·소매점 운영 1-3인 자영업자",
    when: "매일 마감 후 또는 발주 시점",
    why: "엑셀이나 수기 메모로 관리하다 재고 파악 실패, 과잉/부족 발주 반복",
    painPoints: "수기 재고 파악에 하루 1-2시간 소요, 실수로 인한 매출 손실, 발주 타이밍 놓침",
    alternatives: "엑셀, 수기 노트, 기존 POS 재고 기능(복잡함)",
    source: "manual",
    tags: "B2B,자영업,재고관리,SaaS",
    stage: "seed",
    category: "Productivity",
    addedBy: "user",
  },
  {
    title: "1인 개발자·프리랜서의 세금 신고 공포",
    who: "연 매출 1억 미만 1인 사업자, 프리랜서",
    when: "종합소득세 신고 시즌(5월), 부가세 신고(1월·7월)",
    why: "세무사 비용 부담, 스스로 하기엔 복잡, 실수하면 가산세",
    painPoints: "신고 전 2-4주 스트레스, 세무사 비용 연 50-100만원, 어떤 비용이 공제되는지 모름",
    alternatives: "세무사 위임, 홈택스 직접 신고, 삼쩜삼",
    source: "manual",
    tags: "세금,프리랜서,핀테크,1인사업자",
    stage: "seed",
    category: "Fintech",
    addedBy: "user",
  },
  {
    title: "비개발자 창업자의 MVP 개발 병목",
    who: "아이디어는 있지만 코딩 못하는 초기 창업자",
    when: "아이디어 검증 단계, 투자 전",
    why: "외주 개발 비용 높고, 노코드 도구로는 한계, 개발자 공동창업자 찾기 어려움",
    painPoints: "MVP에 500-2000만원 소요, 3-6개월 대기, 요구사항 소통 비용",
    alternatives: "Bubble/Webflow 노코드, 외주 개발사, 개발자 공동창업자",
    source: "yc",
    sourceUrl: "https://www.ycombinator.com/companies",
    tags: "노코드,MVP,개발,B2C",
    stage: "seed",
    category: "Developer Tools",
    addedBy: "scout",
  },
  {
    title: "중소기업 HR 담당자의 채용 후보자 관리 혼란",
    who: "채용 담당 1-2명인 중소기업(50-200인)",
    when: "채용 공고 오픈 후 ~ 최종 합격 통보까지",
    why: "지원자 수백 명을 이메일·엑셀로 관리, 누락 발생, 면접 일정 조율 비효율",
    painPoints: "지원자 연락 누락, 면접 일정 충돌, 채용 과정 가시성 부족, 팀 간 소통 비용",
    alternatives: "엑셀, 노션, 사람인 채용관리, Greenhouse(비쌈)",
    source: "manual",
    tags: "HR,채용,B2B,SaaS",
    stage: "seed",
    category: "HR Tech",
    addedBy: "scout",
  },
  {
    title: "커리어 전환자의 포트폴리오·이력서 차별화 어려움",
    who: "타 직군에서 UX/개발/마케팅으로 전환하려는 25-35세",
    when: "이직 준비 6개월-1년",
    why: "실무 경험 없이 어필할 수단이 부족, 어떤 스킬을 보여줘야 할지 모름",
    painPoints: "서류 통과율 5% 미만, 포트폴리오 피드백 받을 곳 없음, 무엇을 만들어야 할지 모름",
    alternatives: "인프런·유데미 강의, 부트캠프, 멘토링 서비스",
    source: "producthunt",
    tags: "커리어,B2C,에듀테크,취업",
    stage: "seed",
    category: "Education",
    addedBy: "scout",
  },
  {
    title: "소규모 콘텐츠 크리에이터의 브랜드 협찬 계약·정산 복잡성",
    who: "구독자 1만-10만 유튜버·인스타그래머",
    when: "브랜드 협찬 계약 협상 및 정산",
    why: "계약서 검토 비용·지식 없음, 정산 지연, 여러 브랜드 관계 관리 복잡",
    painPoints: "불공정 계약 모름, 정산 평균 45-60일 지연, 세금계산서 발행 번거로움",
    alternatives: "개인 스프레드시트, MCN 소속(수수료 높음), 카카오비즈보드",
    source: "manual",
    tags: "크리에이터,B2C,핀테크,크리에이터이코노미",
    stage: "seed",
    category: "Creator Economy",
    addedBy: "scout",
  },
  {
    title: "병원 대기 환자의 예약·대기 시간 불투명성",
    who: "1차 의원 방문 30-60대 환자",
    when: "병원 예약 및 당일 대기 중",
    why: "예상 대기 시간 모름, 전화 예약 불편, 취소·변경 어려움",
    painPoints: "평균 45분 대기, 전화 연결 10분 이상, 당일 노쇼 증가",
    alternatives: "네이버 예약(대형 병원만), 전화, 직접 방문",
    source: "a16z",
    tags: "헬스케어,B2C,O2O,예약",
    stage: "seed",
    category: "Healthcare",
    addedBy: "scout",
  },
  {
    title: "원격 팀의 비동기 의사결정 기록 소실",
    who: "5-30인 원격/하이브리드 스타트업",
    when: "슬랙·이메일에서 결정 후 문서화 안 됨",
    why: "중요 결정이 슬랙 스레드에 묻혀 사라짐, 신규 입사자 온보딩 비효율",
    painPoints: "\"왜 이렇게 결정했지?\" 반복 논의, 맥락 파악 1-2주 소요, 책임 소재 불명확",
    alternatives: "노션, 컨플루언스, 슬랙 검색(비효율)",
    source: "yc",
    tags: "B2B,SaaS,원격근무,의사결정",
    stage: "series-a",
    category: "Productivity",
    addedBy: "scout",
  },
];

export async function POST() {
  const existing = await prisma.problemCard.count();
  if (existing > 0) {
    return NextResponse.json({ message: "Already seeded", count: existing });
  }
  await prisma.problemCard.createMany({ data: SEED_PROBLEMS });
  return NextResponse.json({ message: "Seeded", count: SEED_PROBLEMS.length });
}
